apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: multi-tier-app
  labels:
    app: postgres
    tier: database
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP