apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: multi-tier-app
  labels:
    app: api-tier
spec:
  selector:
    app: api-tier
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP